WIP - Cylindrical bearing ross standardization
ross-rotordynamics/ross pull request #879
Opened 2022-03-22 17:20 UTC by elyqg

Cylindrical bearing ross standardization

2022-04-11 13:29 UTC, raphaeltimbo requested changes

2022-04-11 13:29 UTC, raphaeltimbo commented on ross/fluid_flow/cylindrical.py
> +        super().__init__(node,kxx,cxx,kyy,kxy,kyx,cyy,cxy,cyx)
The `super().__init__` call does not have the `frequency` argument here. This way, we can only have a bearing with constant coefficients instantiated. We should have a way to call `THDCylindrical(..., frequency=array`), to calculate the coefficients to different frequencies and pass that to the `super().__init__()` call.

2022-04-19 19:33 UTC, elyqg commented
Hi @raphaeltimbo. The proposed corrections have been finalized. If something is still wrong, just let us know and we'll fix it.

2022-04-26 15:05 UTC, raphaeltimbo approved these changes

2022-04-26 15:07 UTC, merged

2022-04-26 15:08 UTC, raphaeltimbo commented
Merged the code.
Thank you @elyqg and @marcusfilipesr !